import {
  AppUser,
  Asset,
  AuditLog,
  PlatformSettings,
  ReportRecord,
  RiskAssessment,
  SecurityControl,
  Threat,
  Vulnerability,
} from "../types";
import { calculateRisk } from "./riskCalculator";
import { generateRecommendation } from "./recommendationEngine";
import { getAssetImpactValue, uid } from "./utils";

const now = new Date();

function ago(days: number) {
  const date = new Date(now);
  date.setDate(date.getDate() - days);
  return date.toISOString();
}

export const demoUsers: AppUser[] = [
  {
    id: "user-admin",
    fullName: "Dilshod Karimov",
    email: "admin@cyberrisk.uz",
    role: "Super Admin",
    organization: "National Digital Services Agency",
    status: "Active",
    createdAt: ago(180),
    password: "Admin123!",
  },
  {
    id: "user-analyst",
    fullName: "Malika Tursunova",
    email: "analyst@cyberrisk.uz",
    role: "Kiberxavfsizlik Analitigi",
    organization: "National Digital Services Agency",
    status: "Active",
    createdAt: ago(130),
    password: "Analyst123!",
  },
  {
    id: "user-auditor",
    fullName: "Akmal Rashidov",
    email: "auditor@cyberrisk.uz",
    role: "Auditor",
    organization: "National Digital Services Agency",
    status: "Active",
    createdAt: ago(120),
    password: "Auditor123!",
  },
  {
    id: "user-org",
    fullName: "Nodir Alimuhamedov",
    email: "user@cyberrisk.uz",
    role: "Tashkilot foydalanuvchisi",
    organization: "Digital University",
    status: "Active",
    createdAt: ago(90),
    password: "User123!",
  },
];

export const demoAssets: Asset[] = [
  {
    id: "asset-main-db",
    assetName: "Main Database Server",
    assetType: "Ma'lumotlar bazasi",
    organization: "Digital University",
    owner: "Database Team",
    criticality: "Kritik",
    confidentialityScore: 5,
    integrityScore: 5,
    availabilityScore: 4,
    businessImpact: "Talaba, to'lov va akademik yozuvlarni saqlaydi.",
    status: "Active",
    createdAt: ago(120),
  },
  {
    id: "asset-web-portal",
    assetName: "Customer Web Portal",
    assetType: "Web ilova",
    organization: "Digital University",
    owner: "Web Operations",
    criticality: "Yuqori",
    confidentialityScore: 4,
    integrityScore: 4,
    availabilityScore: 5,
    businessImpact: "Jamoatga ochiq xizmatlar va foydalanuvchi self-service portali.",
    status: "Active",
    createdAt: ago(112),
  },
  {
    id: "asset-payment-api",
    assetName: "Payment API Gateway",
    assetType: "API servis",
    organization: "FinTech Research Lab",
    owner: "API Security Team",
    criticality: "Kritik",
    confidentialityScore: 5,
    integrityScore: 5,
    availabilityScore: 5,
    businessImpact: "Moliyaviy tranzaksiyalar va tashqi integratsiyalarni boshqaradi.",
    status: "Active",
    createdAt: ago(106),
  },
  {
    id: "asset-email",
    assetName: "Employee Email System",
    assetType: "Foydalanuvchi akkaunti",
    organization: "National Digital Services Agency",
    owner: "Identity Team",
    criticality: "Yuqori",
    confidentialityScore: 4,
    integrityScore: 3,
    availabilityScore: 4,
    businessImpact: "Xodimlar kommunikatsiyasi va audit izi uchun muhim.",
    status: "Under Review",
    createdAt: ago(99),
  },
  {
    id: "asset-cloud",
    assetName: "Cloud Storage Service",
    assetType: "Bulutli xizmat",
    organization: "Digital University",
    owner: "Cloud Governance",
    criticality: "Yuqori",
    confidentialityScore: 4,
    integrityScore: 4,
    availabilityScore: 4,
    businessImpact: "Zaxira fayllar va ilmiy hujjatlar shu yerda saqlanadi.",
    status: "Active",
    createdAt: ago(95),
  },
  {
    id: "asset-mobile",
    assetName: "Mobile Banking App",
    assetType: "Mobil ilova",
    organization: "FinTech Research Lab",
    owner: "Mobile Security Team",
    criticality: "Kritik",
    confidentialityScore: 5,
    integrityScore: 4,
    availabilityScore: 4,
    businessImpact: "Mijoz autentifikatsiyasi va tranzaksiya boshqaruvi.",
    status: "Active",
    createdAt: ago(87),
  },
  {
    id: "asset-hr",
    assetName: "Internal HR System",
    assetType: "Server",
    organization: "National Digital Services Agency",
    owner: "HR Tech",
    criticality: "O'rta",
    confidentialityScore: 3,
    integrityScore: 4,
    availabilityScore: 3,
    businessImpact: "Kadrlar ma'lumotlari va ichki workflow larni boshqaradi.",
    status: "Active",
    createdAt: ago(72),
  },
  {
    id: "asset-backup",
    assetName: "Backup Server",
    assetType: "Fayl server",
    organization: "Digital University",
    owner: "Infrastructure Team",
    criticality: "Yuqori",
    confidentialityScore: 4,
    integrityScore: 5,
    availabilityScore: 4,
    businessImpact: "Favqulodda tiklash va arxivlashning asosi.",
    status: "Active",
    createdAt: ago(55),
  },
];

export const demoThreats: Threat[] = [
  {
    id: "threat-sqli",
    threatName: "SQL Injection",
    category: "SQL Injection",
    description: "Web ilovalarda input validation yetarli bo'lmaganda ekspluatatsiya qilinadi.",
    probability: 0.7,
    source: "External",
    severity: "Kritik",
    createdAt: ago(110),
  },
  {
    id: "threat-phishing",
    threatName: "Phishing",
    category: "Phishing",
    description: "Foydalanuvchi akkauntlarini qo'lga kiritishga qaratilgan email hujumlari.",
    probability: 0.5,
    source: "External",
    severity: "Yuqori",
    createdAt: ago(103),
  },
  {
    id: "threat-ddos",
    threatName: "DDoS",
    category: "DDoS",
    description: "Xizmatdan foydalanishni to'suvchi yuqori hajmdagi trafik.",
    probability: 0.5,
    source: "External",
    severity: "Yuqori",
    createdAt: ago(100),
  },
  {
    id: "threat-ransomware",
    threatName: "Ransomware",
    category: "Ransomware",
    description: "Ma'lumotlarni shifrlab, tiklash uchun to'lov talab qiladi.",
    probability: 0.7,
    source: "Hybrid",
    severity: "Kritik",
    createdAt: ago(95),
  },
  {
    id: "threat-unauthorized",
    threatName: "Unauthorized Access",
    category: "Unauthorized Access",
    description: "Noqonuniy login va lateral movement senariylari.",
    probability: 0.7,
    source: "Hybrid",
    severity: "Yuqori",
    createdAt: ago(91),
  },
  {
    id: "threat-api",
    threatName: "API Abuse",
    category: "API Abuse",
    description: "Rate limiting yoki token nazorati zaif bo'lgan joylarda abuse holatlari.",
    probability: 0.5,
    source: "External",
    severity: "Yuqori",
    createdAt: ago(85),
  },
  {
    id: "threat-insider",
    threatName: "Insider Threat",
    category: "Insider Threat",
    description: "Ichki foydalanuvchi yoki pudratchi sababli ma'lumot oqishi.",
    probability: 0.3,
    source: "Internal",
    severity: "O'rta",
    createdAt: ago(80),
  },
  {
    id: "threat-data",
    threatName: "Data Leakage",
    category: "Data Leakage",
    description: "Bulutli servis yoki noto'g'ri access control sababli oqish ehtimoli.",
    probability: 0.5,
    source: "Hybrid",
    severity: "Yuqori",
    createdAt: ago(76),
  },
];

export const demoVulnerabilities: Vulnerability[] = [
  {
    id: "vuln-input",
    vulnerabilityName: "Input validation yo'qligi",
    category: "Input validation error",
    description: "Kiritmalar sanitizatsiya qilinmaydi.",
    severityLevel: "Kritik",
    severityScore: 1,
    affectedAsset: "asset-web-portal",
    detectionMethod: "DAST va kod review",
    createdAt: ago(90),
  },
  {
    id: "vuln-password",
    vulnerabilityName: "Zaif parol siyosati",
    category: "Weak password policy",
    description: "Minimal murakkablik va rotation talablari yo'q.",
    severityLevel: "Yuqori",
    severityScore: 0.75,
    affectedAsset: "asset-email",
    detectionMethod: "IAM audit",
    createdAt: ago(89),
  },
  {
    id: "vuln-version",
    vulnerabilityName: "Eskirgan server versiyasi",
    category: "Outdated software",
    cveId: "CVE-2025-2784",
    description: "Patch level so'nggi baseline ga mos emas.",
    severityLevel: "Yuqori",
    severityScore: 0.75,
    affectedAsset: "asset-main-db",
    detectionMethod: "Infrastructure scan",
    createdAt: ago(84),
  },
  {
    id: "vuln-ports",
    vulnerabilityName: "Ochiq portlar",
    category: "Open port",
    description: "Keraksiz management portlar internetga ochiq.",
    severityLevel: "O'rta",
    severityScore: 0.5,
    affectedAsset: "asset-backup",
    detectionMethod: "Network scan",
    createdAt: ago(74),
  },
  {
    id: "vuln-backup",
    vulnerabilityName: "Backup siyosati yetarli emas",
    category: "Missing backup",
    description: "Immutable backup va restore testlar yo'q.",
    severityLevel: "Yuqori",
    severityScore: 0.75,
    affectedAsset: "asset-cloud",
    detectionMethod: "BCP audit",
    createdAt: ago(70),
  },
  {
    id: "vuln-mfa",
    vulnerabilityName: "MFA mavjud emas",
    category: "Authentication weakness",
    description: "Administrator va VIP userlar uchun MFA yoqilmagan.",
    severityLevel: "Kritik",
    severityScore: 1,
    affectedAsset: "asset-mobile",
    detectionMethod: "Access control review",
    createdAt: ago(64),
  },
  {
    id: "vuln-logs",
    vulnerabilityName: "Log monitoring zaif",
    category: "Lack of monitoring",
    description: "SIEM use-case lar yetarli emas.",
    severityLevel: "O'rta",
    severityScore: 0.5,
    affectedAsset: "asset-hr",
    detectionMethod: "SOC review",
    createdAt: ago(58),
  },
  {
    id: "vuln-rate",
    vulnerabilityName: "API rate limiting yo'q",
    category: "Insecure API",
    description: "Request throttling va abuse protection yo'q.",
    severityLevel: "Yuqori",
    severityScore: 0.75,
    affectedAsset: "asset-payment-api",
    detectionMethod: "API security test",
    createdAt: ago(46),
  },
];

export const demoControls: SecurityControl[] = [
  {
    id: "control-waf",
    controlName: "Web Application Firewall",
    framework: "OWASP ASVS",
    controlType: "Technical",
    description: "Web traffic inspection va anomaly blocking.",
    effectivenessLevel: "O'rta",
    effectivenessScore: 0.6,
    implementationStatus: "Implemented",
    owner: "Web Security Team",
    createdAt: ago(120),
  },
  {
    id: "control-mfa",
    controlName: "Multi-Factor Authentication",
    framework: "NIST CSF 2.0",
    controlType: "Preventive",
    description: "MFA for privileged and remote access.",
    effectivenessLevel: "Kuchli",
    effectivenessScore: 0.4,
    implementationStatus: "Partially Implemented",
    owner: "Identity Team",
    createdAt: ago(118),
  },
  {
    id: "control-siem",
    controlName: "SIEM Monitoring",
    framework: "NIST SP 800-30",
    controlType: "Detective",
    description: "Centralized logging and detection use cases.",
    effectivenessLevel: "O'rta",
    effectivenessScore: 0.6,
    implementationStatus: "Implemented",
    owner: "SOC Team",
    createdAt: ago(110),
  },
  {
    id: "control-backup",
    controlName: "Daily Backup",
    framework: "ISO/IEC 27001",
    controlType: "Corrective",
    description: "Daily backup schedule with restoration drills.",
    effectivenessLevel: "Zaif",
    effectivenessScore: 0.8,
    implementationStatus: "Partially Implemented",
    owner: "Infrastructure Team",
    createdAt: ago(105),
  },
  {
    id: "control-endpoint",
    controlName: "Endpoint Protection",
    framework: "CIS Controls",
    controlType: "Technical",
    description: "EDR and malware scanning for endpoints.",
    effectivenessLevel: "Kuchli",
    effectivenessScore: 0.4,
    implementationStatus: "Implemented",
    owner: "Endpoint Team",
    createdAt: ago(96),
  },
  {
    id: "control-rbac",
    controlName: "Role Based Access Control",
    framework: "ISO/IEC 27001",
    controlType: "Administrative",
    description: "Least privilege access reviews and segregation of duties.",
    effectivenessLevel: "Kuchli",
    effectivenessScore: 0.4,
    implementationStatus: "Implemented",
    owner: "Governance Team",
    createdAt: ago(92),
  },
  {
    id: "control-firewall",
    controlName: "Network Firewall",
    framework: "NIST CSF 2.0",
    controlType: "Preventive",
    description: "Network segmentation and perimeter filtering.",
    effectivenessLevel: "O'rta",
    effectivenessScore: 0.6,
    implementationStatus: "Implemented",
    owner: "Network Team",
    createdAt: ago(88),
  },
  {
    id: "control-awareness",
    controlName: "Security Awareness Training",
    framework: "CIS Controls",
    controlType: "Administrative",
    description: "Quarterly phishing simulation and staff awareness training.",
    effectivenessLevel: "Zaif",
    effectivenessScore: 0.8,
    implementationStatus: "Partially Implemented",
    owner: "HR Security Liaison",
    createdAt: ago(80),
  },
];

function buildAssessment(
  assetId: string,
  threatId: string,
  vulnerabilityId: string,
  controlId: string,
  assessedBy: string,
  daysAgo: number,
): RiskAssessment {
  const asset = demoAssets.find((item) => item.id === assetId)!;
  const threat = demoThreats.find((item) => item.id === threatId)!;
  const vulnerability = demoVulnerabilities.find((item) => item.id === vulnerabilityId)!;
  const control = demoControls.find((item) => item.id === controlId)!;
  const impactValue = getAssetImpactValue(asset);
  const result = calculateRisk({
    threatProbability: threat.probability,
    vulnerabilityLevel: vulnerability.severityScore,
    impactValue,
    controlWeakness: control.effectivenessScore,
  });

  return {
    id: uid("risk"),
    assetId,
    threatId,
    vulnerabilityId,
    controlId,
    threatProbability: threat.probability,
    vulnerabilityLevel: vulnerability.severityScore,
    impactValue,
    controlWeakness: control.effectivenessScore,
    riskScore: result.score,
    riskLevel: result.level,
    recommendations: generateRecommendation(result.level, threat.category),
    assessedBy,
    createdAt: ago(daysAgo),
  };
}

export const demoRiskAssessments: RiskAssessment[] = [
  buildAssessment("asset-web-portal", "threat-sqli", "vuln-input", "control-waf", "user-analyst", 52),
  buildAssessment("asset-main-db", "threat-ransomware", "vuln-version", "control-backup", "user-analyst", 49),
  buildAssessment("asset-email", "threat-phishing", "vuln-password", "control-awareness", "user-analyst", 45),
  buildAssessment("asset-payment-api", "threat-api", "vuln-rate", "control-firewall", "user-analyst", 40),
  buildAssessment("asset-cloud", "threat-data", "vuln-backup", "control-backup", "user-analyst", 36),
  buildAssessment("asset-mobile", "threat-unauthorized", "vuln-mfa", "control-mfa", "user-analyst", 33),
  buildAssessment("asset-hr", "threat-insider", "vuln-logs", "control-siem", "user-analyst", 28),
  buildAssessment("asset-backup", "threat-ddos", "vuln-ports", "control-firewall", "user-analyst", 25),
];

export const demoAuditLogs: AuditLog[] = [
  {
    id: uid("audit"),
    userId: "user-admin",
    userName: "Dilshod Karimov",
    action: "Platforma ishga tushirildi",
    entityType: "System",
    entityId: "bootstrap",
    ipAddress: "127.0.0.1",
    status: "Success",
    createdAt: ago(20),
  },
  {
    id: uid("audit"),
    userId: "user-analyst",
    userName: "Malika Tursunova",
    action: "Risk baholash yaratildi",
    entityType: "RiskAssessment",
    entityId: demoRiskAssessments[0].id,
    ipAddress: "127.0.0.1",
    status: "Success",
    createdAt: ago(17),
  },
  {
    id: uid("audit"),
    userId: "user-auditor",
    userName: "Akmal Rashidov",
    action: "Audit log ko'rib chiqildi",
    entityType: "Audit",
    entityId: "audit-review",
    ipAddress: "127.0.0.1",
    status: "Success",
    createdAt: ago(14),
  },
];

export const demoReports: ReportRecord[] = [
  {
    id: uid("report"),
    organization: "Digital University",
    fromDate: ago(60),
    toDate: now.toISOString(),
    riskLevel: "Yuqori",
    format: "PDF",
    generatedBy: "Malika Tursunova",
    createdAt: ago(7),
    itemCount: 5,
    summary: "Kritik va yuqori risklar bo'yicha boshqaruv xulosasi tayyorlangan.",
  },
];

export const defaultSettings: PlatformSettings = {
  defaultOrganization: "Digital University",
  preferredFramework: "NIST CSF 2.0",
  reportOwner: "Cyber Risk Office",
  enableEmailAlerts: true,
  enablePrintBranding: true,
  riskThresholds: {
    lowMax: 24,
    mediumMax: 49,
    highMax: 74,
  },
};

export function createSeedState() {
  return {
    assets: demoAssets,
    threats: demoThreats,
    vulnerabilities: demoVulnerabilities,
    controls: demoControls,
    riskAssessments: demoRiskAssessments,
    auditLogs: demoAuditLogs,
    users: demoUsers,
    reports: demoReports,
    settings: defaultSettings,
  };
}
