import { useMemo, useState } from "react";
import { ReportBuilder, ReportFormValue } from "../../components/reports/ReportBuilder";
import { ReportPreview } from "../../components/reports/ReportPreview";
import { DataTable } from "../../components/ui/DataTable";
import { Badge } from "../../components/ui/Badge";
import { usePlatform } from "../../lib/platform-context";
import { downloadTextFile, formatDate } from "../../lib/utils";
import { ReportRecord } from "../../types";

function reportHtml(report: ReportRecord, organization: string) {
  return `
    <html>
      <head><meta charset="utf-8"><title>${organization} report</title></head>
      <body>
        <h1>CyberRisk Probability Assessment Platform</h1>
        <h2>${organization}</h2>
        <p>Format: ${report.format}</p>
        <p>Generated by: ${report.generatedBy}</p>
        <p>Summary: ${report.summary}</p>
      </body>
    </html>
  `;
}

export function ReportsPage() {
  const { assets, threats, vulnerabilities, riskAssessments, auditLogs, reports, generateReport } = usePlatform();
  const organizations = Array.from(new Set(assets.map((item) => item.organization)));
  const [value, setValue] = useState<ReportFormValue>({
    organization: organizations[0] ?? "Digital University",
    fromDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString().slice(0, 10),
    toDate: new Date().toISOString().slice(0, 10),
    riskLevel: "Barchasi",
    format: "PDF",
  });
  const [preview, setPreview] = useState<ReportRecord | null>(reports[0] ?? null);

  const filteredAssessments = useMemo(
    () =>
      riskAssessments.filter((item) => {
        const asset = assets.find((entry) => entry.id === item.assetId);
        const created = item.createdAt.slice(0, 10);
        const matchesOrg = asset?.organization === value.organization;
        const matchesDates = created >= value.fromDate && created <= value.toDate;
        const matchesLevel = value.riskLevel === "Barchasi" || item.riskLevel === value.riskLevel;
        return matchesOrg && matchesDates && matchesLevel;
      }),
    [assets, riskAssessments, value],
  );

  function handleGenerate() {
    const report = generateReport(value);
    setPreview(report);
  }

  function handleExport() {
    if (!preview) {
      return;
    }

    if (value.format === "PDF") {
      window.print();
      return;
    }

    if (value.format === "DOCX") {
      downloadTextFile("cyberrisk-report.doc", reportHtml(preview, value.organization), "application/msword");
      return;
    }

    const csvRows = [
      ["Asset", "Threat", "Risk Level", "Risk Score"],
      ...filteredAssessments.map((assessment) => [
        assets.find((item) => item.id === assessment.assetId)?.assetName ?? "",
        threats.find((item) => item.id === assessment.threatId)?.threatName ?? "",
        assessment.riskLevel,
        String(assessment.riskScore),
      ]),
    ];
    downloadTextFile(
      "cyberrisk-report.csv",
      csvRows.map((row) => row.join(",")).join("\n"),
      "text/csv;charset=utf-8",
    );
  }

  return (
    <div className="space-y-6">
      <div className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr]">
        <div className="space-y-6">
          <ReportBuilder organizations={organizations} value={value} onChange={setValue} onGenerate={handleGenerate} />
          <div className="panel rounded-3xl p-6">
            <h3 className="text-lg font-semibold text-slate-950">Export actions</h3>
            <p className="mt-1 text-sm text-slate-500">
              PDF uchun brauzer print, DOCX uchun HTML-based Word export, XLSX uchun CSV-compatible eksport ishlaydi.
            </p>
            <div className="mt-5 flex flex-wrap gap-3">
              <button
                type="button"
                onClick={handleGenerate}
                className="rounded-2xl border border-slate-200 bg-white px-5 py-3 text-sm font-semibold text-slate-700"
              >
                Preview yangilash
              </button>
              <button
                type="button"
                onClick={handleExport}
                className="rounded-2xl bg-[var(--primary)] px-5 py-3 text-sm font-semibold text-white"
              >
                Export qilish
              </button>
            </div>
          </div>
        </div>

        <ReportPreview
          report={preview}
          assessments={filteredAssessments}
          assets={assets}
          threats={threats}
          vulnerabilities={vulnerabilities}
          auditLogs={auditLogs}
        />
      </div>

      <DataTable
        title="Yaratilgan hisobotlar"
        data={reports}
        emptyTitle="Hisobot topilmadi"
        emptyDescription="Preview yaratish orqali hisobotlar tarixini to'ldiring."
        columns={[
          {
            key: "organization",
            header: "Tashkilot",
            render: (report) => report.organization,
          },
          {
            key: "period",
            header: "Period",
            render: (report) => `${formatDate(report.fromDate)} - ${formatDate(report.toDate)}`,
          },
          {
            key: "level",
            header: "Risk",
            render: (report) => <Badge variant="blue">{report.riskLevel}</Badge>,
          },
          {
            key: "format",
            header: "Format",
            render: (report) => report.format,
          },
          {
            key: "items",
            header: "Items",
            render: (report) => report.itemCount,
          },
        ]}
      />
    </div>
  );
}
